trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: centralized
      type: github
      name: naidu72/centralized-repo
      ref: refs/heads/main
      endpoint: naidu72git

extends:
  template: templates/hello-template.yml@centralized
  parameters:
    appName: 'app1'

